spring:
  thymeleaf:
    cache: false
  # 配置国际化
  messages:
    basename: i18n.login
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/stus?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC


server:
  port: 8080

mybatis:
  type-aliases-package: com.damon.springBoot.pojo
  mapper-locations: classpath:mapper/*.xml



